apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-ha.fullname" . }}
  labels:
    {{- include "nginx-ha.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nginx-ha.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nginx-ha.labels" . | nindent 8 }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          livenessProbe: # necessary for high availability as it uses health check
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe: # necessary for load balancer to know when pod is ready
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf # Mount the config file from ConfigMap
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "nginx-ha.fullname" . }}-config